image: python:3
lint:
 stage: test
 script:
  - pip install yapf==0.32.0
  - yapf --style google --recursive --diff .
 merge_requests:
  - pushes

unittest:
 stage: test
 script:
  - pip install -r requirements.txt
  - pytest .
 merge_requests:
  - pushes

prod:
 image: google/cloud-sdk:alpine
 stage: deploy
 environment: Production
 merge_requests:
 - main
 script:
 - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
 - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
 - gcloud --quiet --project wikigroup10 app deploy
 - gcloud app browse --project $PROJECT_ID